package dev.barna.calm

data class LauncherUiPreferences(
    val useTintedNotificationCards: Boolean,
    val useCardIconBackgrounds: Boolean,
    val cardCornerRadiusDp: Int,
    val cardIconBlur: Int,
    val focusBlurRadius: Int,
    val splitAppsByProfile: Boolean,
    val placeWorkNotificationChaptersBeforeApps: Boolean,
    val cardHapticsEnabled: Boolean,
    val cardHapticStrength: Int,
    val cardStackTuning: CardStackTuning,
    val showAdvancedStackControls: Boolean,
    val cardVibrancy: Int,
    val fullScreenModeEnabled: Boolean = false,
    val pageSortOrder: PageSortOrder = PageSortOrder.DEFAULT,
    val expandedCardsEnabled: Boolean = true,
    val pinnedPageEnabled: Boolean = false,
    val contactsPageEnabled: Boolean = false,
    val agendaPageEnabled: Boolean = false,
    val alarmsPageEnabled: Boolean = false,
    val rssPageEnabled: Boolean = false,
    val agendaSectionMode: CardStackSectionMode = CardStackSectionMode.TITLE_CARDS,
    val agendaSectionTitleStyle: SectionTitleCardStyle = SectionTitleCardStyle(),
    val cardAppearance: CardAppearance = CardAppearance.DEFAULT,
    val pageLayout: LauncherPageLayout = LauncherPageLayout.DEFAULT,
    val chapterSpineStyle: ChapterSpineStyle = ChapterSpineStyle.DEFAULT,
)
